### ISSUE TITLE
Dataser_not_found

### ISSUE THREAD

**Issue by Syed-Hamza-Ali** [Beeditor04/Glasses-Frame-Recommendation-System#1]
in file 0_Collect_and_organize, we need to give train dataset but it's not given
dir_path = os.path.join('./cropped_dataset/train/', folder)

**Comment by Beeditor04** [comment]
oh yeah sorry I use my private dataset on my kaggle, and I'm planning on completing this project at the end of the month for documentation and additional features, so feel free to keep in touch
